-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 11:00:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coracaosolidario_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coracaosolidario_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coracaosolidario_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `coracaosolidario_db` ;

-- -----------------------------------------------------
-- Table `coracaosolidario_db`.`doadores_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracaosolidario_db`.`doadores_tb` (
  `id` BIGINT NOT NULL,
  `tipo` ENUM('Pessoa', 'Instituição') NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `registro` ENUM('CPF', 'CNPJ') NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(255) NULL,
  `data_registro` DATE NOT NULL,
  `login` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coracaosolidario_db`.`categorias_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracaosolidario_db`.`categorias_tb` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coracaosolidario_db`.`doacoes_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coracaosolidario_db`.`doacoes_tb` (
  `id` BIGINT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `destino` VARCHAR(255) NOT NULL,
  `data_doacao` DATE NULL,
  `doadores_tb_id` BIGINT NOT NULL,
  `categorias_tb_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `doadores_tb_id`, `categorias_tb_id`),
  INDEX `fk_doacoes_tb_doadores_tb_idx` (`doadores_tb_id` ASC) VISIBLE,
  INDEX `fk_doacoes_tb_categorias_tb1_idx` (`categorias_tb_id` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_tb_doadores_tb`
    FOREIGN KEY (`doadores_tb_id`)
    REFERENCES `coracaosolidario_db`.`doadores_tb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacoes_tb_categorias_tb1`
    FOREIGN KEY (`categorias_tb_id`)
    REFERENCES `coracaosolidario_db`.`categorias_tb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
